const scholarships=[
{name:"MOE Pre-University Scholarship",provider:"Ministry of Education",levels:["JC"],field:"All fields",eligibility:"Singapore Citizen",award:"Tuition + allowance",deadline:"Check official site",tags:["JC","Government"],url:"https://www.moe.gov.sg/financial-matters/awards-scholarships/scholarships"},
{name:"MOE Teaching Scholarship",provider:"Ministry of Education",levels:["JC","University"],field:"Education",eligibility:"Singapore Citizen",award:"Full sponsorship",deadline:"Annual",tags:["JC","Education"],url:"https://www.moe.gov.sg/careers/scholarships"},
{name:"NUS Global Merit Scholarship",provider:"National University of Singapore",levels:["University"],field:"Multiple disciplines",eligibility:"Eligible applicants",award:"Tuition + allowances",deadline:"Annual",tags:["University","Merit"],url:"https://www.nus.edu.sg/oam/scholarships/scholarships-for-freshmen-singapore-citizens"},
{name:"NUS Science & Technology Undergraduate Scholarship",provider:"National University of Singapore",levels:["University"],field:"Computing / Engineering / Science",eligibility:"Eligible international applicants",award:"Tuition + living allowance",deadline:"Annual",tags:["University","STEM"],url:"https://www.nus.edu.sg/oam/scholarships/scholarships-for-freshmen-international-students"},
{name:"NTU Nanyang Scholarship",provider:"Nanyang Technological University",levels:["University"],field:"Multiple disciplines",eligibility:"Singapore Citizen / PR / International",award:"Tuition + living allowance",deadline:"Annual",tags:["University","Merit"],url:"https://www.ntu.edu.sg/admissions/undergraduate/scholarships"},
{name:"NTU Science & Engineering Undergraduate Scholarship",provider:"Nanyang Technological University",levels:["University"],field:"Science / Engineering",eligibility:"Eligible applicants",award:"Tuition + allowance",deadline:"Annual",tags:["University","STEM"],url:"https://www.ntu.edu.sg/admissions/undergraduate/scholarships"},
{name:"SMU Lee Kong Chian Scholars Programme",provider:"Singapore Management University",levels:["University"],field:"Multiple disciplines",eligibility:"Outstanding applicants",award:"Tuition + allowances",deadline:"Annual",tags:["University","Merit"],url:"https://admissions.smu.edu.sg/financial-aid/scholarships"},
{name:"SMU Global Impact Scholarship",provider:"Singapore Management University",levels:["University"],field:"Multiple disciplines",eligibility:"Eligible applicants",award:"Tuition support",deadline:"Annual",tags:["University","Leadership"],url:"https://admissions.smu.edu.sg/financial-aid/scholarships"},
{name:"Singtel Undergraduate Scholarship",provider:"Singtel",levels:["University"],field:"Technology / Business / Engineering",eligibility:"Singapore Citizens / PR",award:"Tuition + allowance",deadline:"Annual",tags:["University","STEM"],url:"https://www.singtel.com/about-us/careers/students-and-graduates"},
{name:"A*STAR Science Award",provider:"A*STAR",levels:["Secondary","JC"],field:"Science / Technology",eligibility:"Singapore students (programme-specific)",award:"Award varies",deadline:"Programme dependent",tags:["Secondary","STEM"],url:"https://www.a-star.edu.sg/Scholarships"},
{name:"Public Service Commission Scholarship",provider:"Public Service Commission",levels:["JC","University"],field:"Multiple disciplines",eligibility:"Singapore Citizen",award:"Full scholarship + benefits",deadline:"Annual",tags:["JC","Government"],url:"https://www.psc.gov.sg/scholarships"},
{name:"DSTA Scholarship",provider:"DSTA",levels:["JC","University"],field:"Engineering / Computing / Science",eligibility:"Singapore Citizen",award:"Tuition + allowances",deadline:"Annual",tags:["JC","STEM"],url:"https://www.dsta.gov.sg/careers/scholarships"}];

const grid=document.querySelector("#grid"),input=document.querySelector("#searchInput"),level=document.querySelector("#levelFilter"),count=document.querySelector("#count");
function render(){
 const q=input.value.toLowerCase().trim(), l=level.value;
 const list=scholarships.filter(s=>(!l||s.levels.includes(l))&&(!q||[s.name,s.provider,s.field,s.eligibility,s.award].concat(s.tags,s.levels).join(" ").toLowerCase().includes(q)));
 count.textContent=list.length;
 grid.innerHTML=list.map(function(s){return '<article class="card"><div class="tags">'+s.tags.map(function(t){return '<span class="tag">'+t+'</span>'}).join("")+'</div><h3>'+s.name+'</h3><div class="provider">'+s.provider+'</div><div class="meta"><div><small>Eligibility</small><b>'+s.eligibility+'</b></div><div><small>Award</small><b>'+s.award+'</b></div><div><small>Field</small><b>'+s.field+'</b></div><div><small>Deadline</small><b>'+s.deadline+'</b></div></div><a href="'+s.url+'" target="_blank" rel="noopener">View official source →</a></article>'}).join("")||'<div class="card"><h3>No matching scholarships yet</h3><div class="provider">Try a broader search or remove a filter.</div></div>';
}
input.addEventListener("input",render);level.addEventListener("change",render);document.querySelector("#searchBtn").addEventListener("click",render);
document.querySelectorAll("[data-filter]").forEach(function(b){b.addEventListener("click",function(){level.value=["Secondary","JC","Polytechnic","University"].includes(b.dataset.filter)?b.dataset.filter:"";input.value=b.dataset.filter==="STEM"?"STEM":"";render()})});
render();