const URL="https://xndgplkeayyrtzqgphlj.supabase.co",KEY="sb_publishable_QQ_FVe4_XJA8vaLWg9FXPQ_PwamKnNa";const db=window.supabase?.createClient?window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}}):null;let user,profile,experiences=[],evidence=[],reflections=[],skills=[];
const DIMS=[["Academic",75],["Scientific Thinking",75],["Medical Insight",65],["Service",70],["Leadership",70],["Communication",70],["Reasoning & Ethics",72],["Reflection & Character",70]];
const OPS=[["Deepen an existing service role","Service","Continue a real community commitment and own one outcome.","Evidence + continuity","Certificate-only participation"],["Own a small project","Leadership","Lead planning, coordination, delegation or follow-through.","Ownership + FSA transfer","Title without responsibility"],["Research with a question","Scientific Thinking","Work on a genuine question and produce an artefact.","Reasoning + evidence","One-day exposure"],["Teach or mentor consistently","Communication","Help another student over multiple sessions.","Communication + service","Counting hours only"],["Structured community listening","Service","Understand a need before deciding what to do.","Listening + reflection","Medicine cosplay"],["Debate / discussion depth","Reasoning & Ethics","Practise competing views, evidence and consequences.","Reasoning + communication","Another certificate"]];
const SC=[["A teammate strongly disagrees with your proposal.","What would you do first?"],["A student you mentor is not following the plan.","How would you respond before changing it?"],["You notice a mistake just before submission.","What would you do, and why?"]];
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function go(id){const target=$(id);if(!target)return;document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));target.classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.go===id));window.scrollTo(0,0);render()}
const pages=["dashboard","profile","academics","journey","reflection","growth","opportunities","evidence","portfolio","fsa","application"];
pages.forEach(p=>{const b=document.createElement("button");b.className="nav";b.dataset.go=p;b.textContent=p==="dashboard"?"Dashboard":p.replace(/^./,x=>x.toUpperCase());$("nav").appendChild(b)});
document.addEventListener("click",e=>{const b=e.target.closest("[data-go]");if(b){e.preventDefault();go(b.dataset.go)}});
$("signOut").onclick=async()=>{try{if(db)await db.auth.signOut()}finally{location.href="index.html"}};
async function init(){if(!db){$("userName").textContent="Offline";return}let s=await db.auth.getSession();user=s.data.session?.user;if(!user){location.href="index.html";return}let r=await db.auth.refreshSession();user=r.data.session?.user||user;$("userName").textContent=user.user_metadata?.display_name||user.email;await load();render()}
async function load(){let q=await Promise.all([db.from("candidate_profiles").select("*").eq("user_id",user.id).maybeSingle(),db.from("experiences").select("*").eq("user_id",user.id).order("year",{ascending:false}),db.from("evidence").select("*").eq("user_id",user.id).order("created_at",{ascending:false}),db.from("reflections").select("*").eq("user_id",user.id),db.from("skill_assessments").select("*").eq("user_id",user.id)]);profile=q[0].data;experiences=q[1].data||[];evidence=q[2].data||[];reflections=q[3].data||[];skills=q[4].data||[];if(!profile){let n={user_id:user.id,display_name:user.user_metadata?.display_name||user.email,stage:"Sec 4",target_programme:"NUS Medicine",current_focus:"Leadership",focus_score:58,target_score:70,profile_data:{},academic_data:{},application_data:{},fsa_data:{},preferences_data:{}};let z=await db.from("candidate_profiles").insert(n).select().single();profile=z.data||n}}
const pd=k=>profile?.profile_data?.[k]??"",ad=k=>profile?.academic_data?.[k]??"",app=k=>profile?.application_data?.[k]??"";
function vals(){let b={Academic:62,"Scientific Thinking":52,"Medical Insight":50,Service:52,Leadership:58,Communication:52,"Reasoning & Ethics":55,"Reflection & Character":55};experiences.forEach(x=>(x.skills||[]).forEach(s=>DIMS.forEach(d=>{if(s===d[0]||s.includes(d[0]))b[d[0]]=Math.min(95,b[d[0]]+6)})));if(reflections.length)b["Reflection & Character"]=Math.min(90,b["Reflection & Character"]+Math.min(18,reflections.length*3));skills.forEach(s=>{const d=DIMS.find(x=>x[0].toLowerCase()===String(s.skill||"").toLowerCase());if(d&&Number(s.current_score)>b[d[0]])b[d[0]]=Number(s.current_score)});return b}
function renderDash(){let v=vals(),g=DIMS.map(d=>({n:d[0],t:d[1],c:v[d[0]],gap:d[1]-v[d[0]]})).sort((a,b)=>b.gap-a.gap);
let profileFields=["school","medicine_motivation","healthcare_interest","interests","commitments","priorities"],profileDone=profileFields.filter(k=>pd(k)).length,academicFields=["route","academic_target","chemistry","biology","gp","project_work"],academicDone=academicFields.filter(k=>ad(k)).length;
let readiness=Math.round((profileDone/6*25)+(academicDone/6*20)+(Math.min(experiences.length,5)/5*20)+(Math.min(evidence.length,5)/5*15)+(Math.min(reflections.length,3)/3*10)+(Math.min(skills.length,3)/3*10));
let appChecks=[!!ad("route"),!!pd("medicine_motivation"),experiences.length>0,evidence.length>0,reflections.length>0,experiences.length>=5,!!app("personal_statement_notes"),["Requested","Draft received","Ready"].includes(app("testimonial")),!!app("referee1"),!!app("referee2")];let appPct=Math.round(appChecks.filter(Boolean).length/appChecks.length*100);
$("stage").textContent=profile?.stage||"Sec 4";$("ready").textContent=readiness+"%";$("expCount").textContent=experiences.length;$("eviCount").textContent=evidence.length;$("refCount").textContent=reflections.length;
$("profilePct").textContent=Math.round(profileDone/6*100)+"%";$("profileCheck").textContent=profileDone===6?"✓":"○";$("academicCheck").textContent=academicDone>=4?"✓":"○";$("experienceCheck").textContent=experiences.length?"✓":"○";$("evidenceCheck").textContent=evidence.length?"✓":"○";
$("next").textContent=!pd("medicine_motivation")?"Complete your candidate profile.":g[0].gap>0?"Close your "+g[0].n+" gap through one meaningful action.":"Strengthen evidence quality and continuity.";
$("nextwhy").textContent="Largest current internal gap: "+g[0].n+" (−"+Math.max(0,g[0].gap)+").";
$("weekTitle").textContent="Close your "+g[0].n+" gap";$("weekText").textContent=g[0].n==="Leadership"?"Take ownership of one real outcome, then capture what changed.":"Choose one sustained action that creates evidence in "+g[0].n+".";
$("weekChecks").innerHTML=["Define the outcome you will own","Do the work and record what changed","Capture one piece of evidence","Write a short reflection"].map((x,i)=>'<div class="task"><span>'+["01","02","03","04"][i]+'</span>'+x+'</div>').join("");
$("weekAction").onclick=()=>go(g[0].n==="Leadership"?"journey":"opportunities");
$("appReady").textContent=appPct+"%";$("appText").textContent=appPct>=80?"Your application layer is taking shape. Keep strengthening the underlying candidate." :"Build the candidate first; application items will become easier to complete.";$("appBar").querySelector("i").style.width=appPct+"%";
$("integrityText").textContent=evidence.length?Math.round(evidence.filter(x=>x.experience_id).length/evidence.length*100)+"% of evidence is linked to a real experience. Every claim should trace back to Experience → Evidence → Reflection.":"No evidence has been added yet. Start by linking one real artefact to an experience.";
$("homeLoop").innerHTML=[["Requirements","requirements",!!ad("route")||!!profile?.target_programme],["Gap","growth",g[0].gap>0],["Action","opportunities",false],["Experience","journey",experiences.length>0],["Evidence","evidence",evidence.length>0],["Reflection","reflection",reflections.length>0],["Growth","growth",g[0].gap<=0],["Portfolio","portfolio",experiences.some(x=>x.portfolio_status==="Candidate")],["FSA","fsa",skills.length>0],["Application","application",appPct>=80]].map((x,i)=>'<button class="loopitem '+(x[2]?"done":"")+'" data-go="'+x[1]+'"><small>0'+(i+1)+'</small><b>'+x[0]+'</b><span>'+(x[2]?"✓ Complete":"Open →")+'</span></button>').join("");
$("dna").innerHTML=DIMS.map(d=>'<div class="card dna"><b>'+d[0]+'</b><strong>'+v[d[0]]+'</strong><small>Target '+d[1]+'</small><div class="bar"><i style="width:'+v[d[0]]+'%"></i></div><div class="gap">'+(d[1]-v[d[0]]>0?"Gap "+(d[1]-v[d[0]]):"On track")+'</div></div>').join("");
document.querySelectorAll(".loopitem").forEach(b=>b.onclick=()=>go(b.dataset.go));
}
function fillForm(id,obj,fields){let f=$(id);fields.forEach(k=>{if(f.elements[k])f.elements[k].value=obj[k]??""})}
function renderProfile(){fillForm("profileForm",Object.assign({display_name:profile?.display_name||user.email,school:profile?.school,stage:profile?.stage||"Sec 4",target_programme:profile?.target_programme||"NUS Medicine"},profile?.profile_data||{}),["display_name","school","stage","target_year","target_programme","location","medicine_motivation","healthcare_interest","interests","commitments","priorities"])}
$("profileForm").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));let d=Object.assign({},profile.profile_data||{},o);let q=await db.from("candidate_profiles").update({display_name:o.display_name,school:o.school,stage:o.stage,target_programme:o.target_programme,profile_data:d,updated_at:new Date().toISOString()}).eq("user_id",user.id);$("profileMsg").textContent=q.error?q.error.message:"Saved.";await load();renderDash()};
function renderAcademics(){fillForm("academicForm",Object.assign({route:"A-Level"},profile?.academic_data||{}),["route","academic_target","chemistry","biology","physics","gp","project_work","other_subjects","strengths","gaps","strategy"])}
$("academicForm").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));let q=await db.from("candidate_profiles").update({academic_data:o,updated_at:new Date().toISOString()}).eq("user_id",user.id);$("academicMsg").textContent=q.error?q.error.message:"Saved.";await load();renderDash()};
function renderReflection(){const el=$("reflectionList");if(!el)return;el.innerHTML=reflections.length?reflections.map(r=>{const x=experiences.find(e=>e.id===r.experience_id)||{};return "<article class='card experience'><h3>"+esc(x.title||"Reflection")+"</h3><p>"+esc(r.what_happened||"")+"</p><div class='chips'><span class='chip'>"+(r.learning?"Learning ✓":"Learning needed")+"</span><span class='chip'>"+(r.what_changed?"Impact ✓":"Impact needed")+"</span></div></article>"}).join(""):"<div class='notice'>No reflections yet. Add a reflection from a real experience.</div>"}
function renderJourney(filter){let xs=experiences;if(filter==="active")xs=xs.filter(x=>["Started","Active"].includes(x.lifecycle_status));if(filter==="reflected")xs=xs.filter(x=>x.learning||reflections.some(r=>r.experience_id===x.id));if(filter==="portfolio")xs=xs.filter(x=>["Candidate","Strong"].includes(x.portfolio_status));$("journeyList").innerHTML=xs.length?xs.map(x=>'<article class="experience"><div><h3>'+esc(x.title)+'</h3><p>'+esc(x.role)+' · '+esc(x.duration||"")+' · '+x.year+'</p><div class="chips">'+(x.skills||[]).map(s=>'<span class="chip">'+esc(s)+'</span>').join("")+'</div><p>'+esc(x.description||"")+'</p><div class="chips"><span class="chip">'+(evidence.some(e=>e.experience_id===x.id)?"Evidence ✓":"Evidence needed")+'</span><span class="chip">'+(x.learning?"Reflection ✓":"Reflection needed")+'</span></div></div><div class="state">'+esc(x.lifecycle_status||"Started")+'<br><button onclick="openExp(\''+x.id+'\')">Open →</button></div></article>').join(""):"<div class='notice'>No experiences yet. Start with something real and substantive.</div>"}
document.querySelectorAll(".filters button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderJourney(b.dataset.filter)}));
$("addExp").onclick=()=>openExp("");
window.openExp=async id=>{let x=experiences.find(e=>e.id===id)||{};$("modalBody").innerHTML='<p class="eyebrow">EXPERIENCE RECORD</p><h2>'+(id?"Edit experience":"Add experience")+'</h2><label>Title<input id="et" value="'+esc(x.title||"")+'"></label><label>Role<input id="er" value="'+esc(x.role||"")+'"></label><div class="grid2"><label>Year<input id="ey" type="number" value="'+(x.year||new Date().getFullYear())+'"></label><label>Duration<input id="ed" value="'+esc(x.duration||"")+'"></label></div><label>What happened?<textarea id="ex">'+esc(x.description||"")+'</textarea><label>What changed / impact?<textarea id="ei">'+esc(x.impact||"")+'</textarea><label>What did you learn?<textarea id="el">'+esc(x.learning||"")+'</textarea><label>Skills developed<input id="es" value="'+esc((x.skills||[]).join(", "))+'"></label><label>Lifecycle<select id="ec"><option>Interested</option><option>Planned</option><option>Started</option><option>Active</option><option>Completed</option><option>Reflected</option><option>Evidence Added</option><option>Impact Assessed</option><option>Portfolio Candidate</option></select></label><div class="modalactions"><button id="saveExp" class="primary">Save</button></div>';$("modal").classList.add("open");if(x.lifecycle_status)$("ec").value=x.lifecycle_status;$("saveExp").onclick=async()=>{let p={user_id:user.id,title:$("et").value.trim(),role:$("er").value.trim(),year:Number($("ey").value),duration:$("ed").value.trim(),description:$("ex").value.trim(),impact:$("ei").value.trim(),learning:$("el").value.trim(),skills:$("es").value.split(",").map(v=>v.trim()).filter(Boolean),lifecycle_status:$("ec").value,portfolio_status:$("ec").value==="Portfolio Candidate"?"Strong":"Supporting"};if(id)await db.from("experiences").update(p).eq("id",id).eq("user_id",user.id);else await db.from("experiences").insert(p);closeModal();await load();render()}}
function renderGrowth(){let v=vals(),g=DIMS.map(d=>({n:d[0],c:v[d[0]],t:d[1],gap:d[1]-v[d[0]]})).sort((a,b)=>b.gap-a.gap);$("growthList").innerHTML=g.map(x=>'<article class="growth"><div><h3>'+x.n+'</h3><small>Current '+x.c+' · Target '+x.t+'</small></div><span class="gapnum">'+(x.gap>0?"−"+x.gap:"✓")+'</span></article>').join("");let x=g[0];$("growthFocus").textContent=x.n;$("growthWhy").textContent="One meaningful action in this area currently has the highest development value.";$("growthDo").textContent=x.n==="Leadership"?"Own one real outcome and record what changed.":"Choose one sustained action that creates real evidence in "+x.n+".";$("growthDont").textContent="Add another shallow activity just to increase activity count."}
function renderOps(){let v=vals(),g=DIMS.map(d=>d[1]-v[d[0]]).sort((a,b)=>b-a);$("opList").innerHTML=OPS.map((o,i)=>'<article class="card op"><span class="match">MATCH · '+(g[i%g.length]>0?"CURRENT GAP":"BUILD")+'</span><h3>'+o[0]+'</h3><p><b>'+o[1]+'</b><br>'+o[2]+'</p><p>Why: '+o[3]+'</p><div class="trap">Avoid: '+o[4]+'</div></article>').join("")}
function renderEvidence(){let ver=evidence.filter(x=>x.verified).length,linked=evidence.filter(x=>x.experience_id).length;$("evTotal").textContent=evidence.length;$("evVerified").textContent=ver;$("evHealth").textContent=(evidence.length?Math.round(linked/evidence.length*100):0)+"%";$("evidenceList").innerHTML=evidence.length?evidence.map(x=>'<article class="card evidence"><h3>'+esc(x.title)+'</h3><p>'+esc(x.evidence_type||"Evidence")+' · '+esc((experiences.find(e=>e.id===x.experience_id)||{}).title||"Unlinked")+'</p><p>'+esc(x.notes||"")+'</p><span class="verified">'+(x.verified?"Verified":"Needs verification")+'</span></article>').join(""):"<div class='notice'>Connect reports, certificates, presentations, mentor feedback, impact data and other real evidence to your experiences.</div>"}
function renderPortfolio(){let xs=experiences.filter(x=>["Strong","Candidate"].includes(x.portfolio_status));$("portfolioSummary").innerHTML='<div class="card"><b>'+xs.length+'</b><span>Portfolio candidates</span></div><div class="card"><b>'+new Set(xs.flatMap(x=>x.skills||[])).size+'</b><span>Capability signals</span></div><div class="card"><b>'+Math.min(100,xs.length*15)+'</b><span>Development depth</span></div>';$("portfolioList").innerHTML=(xs.length?xs:experiences).slice(0,10).map((x,i)=>'<article class="card portfolio"><span class="match">TOP 10 BANK · '+String(i+1).padStart(2,"0")+'</span><h3>'+esc(x.title)+'</h3><p>'+esc(x.role)+' · '+esc(x.duration||"")+'</p><div class="chips">'+(x.skills||[]).map(s=>'<span class="chip">'+esc(s)+'</span>').join("")+'</div><p>Evidence: '+evidence.filter(e=>e.experience_id===x.id).length+' · Reflection: '+(x.learning?"Recorded":"Needed")+'</p></article>').join("")}
function renderFsa(){let v=vals(),a=[["Communication",v.Communication],["Listening",Math.min(90,v.Communication+4)],["Teamwork",Math.min(90,v.Service+8)],["Reasoning",v["Reasoning & Ethics"]],["Adaptability",Math.min(90,v["Reflection & Character"]+5)]];$("fsaSkills").innerHTML=a.map(x=>'<div class="card skill"><b>'+x[0]+'</b><strong>'+x[1]+'</strong><small>development signal</small></div>').join("");let s=SC[Math.floor(Math.random()*SC.length)];$("scenarioTitle").textContent=s[0];$("scenarioPrompt").textContent=s[1]}
$("fsaSubmit").onclick=async()=>{const a=$("fsaAnswer").value.trim();$("fsaFeedback").innerHTML=a?"<b>Practice feedback:</b> Start with listening and clarification. Consider the other person's perspective before defending your own. Then decide, act and reflect.":"Start by listening and clarifying the concern rather than defending your proposal immediately.";if(!a)return;const q=await db.from("skill_assessments").insert({user_id:user.id,skill:"Communication",current_score:Math.min(100,(vals().Communication||50)+6),target_score:70,trend:"up",source:"FSA Practice"});if(q.error)alert(q.error.message);else{await load();render();$("fsaFeedback").innerHTML+="<br><span class=\"verified\">Saved. Candidate DNA and Gap updated.</span>"}};
function renderApp(){let c=[["Academic route",!!ad("route")],["Profile",!!pd("medicine_motivation")],["Experiences",experiences.length>0],["Evidence",evidence.length>0],["Reflections",reflections.length>0],["Top 10 bank",experiences.length>=5],["Personal Statement notes",!!app("personal_statement_notes")],["Testimonial",["Requested","Draft received","Ready"].includes(app("testimonial"))],["Referee 1",!!app("referee1")],["Referee 2",!!app("referee2")]];$("checklist").innerHTML=c.map(x=>'<div class="card check"><b>'+x[0]+'</b><span>'+(x[1]?"✓ Ready":"○ Needed")+'</span></div>').join("");fillForm("applicationForm",Object.assign({},profile?.application_data||{}),["personal_statement_notes","top10_notes","referee1","referee2","testimonial","notes"])}
$("applicationForm").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));let q=await db.from("candidate_profiles").update({application_data:o,updated_at:new Date().toISOString()}).eq("user_id",user.id);$("applicationMsg").textContent=q.error?q.error.message:"Saved.";await load();renderApp()};
function closeModal(){$("modal").classList.remove("open")}$("closeModal").onclick=closeModal;$("modal").onclick=e=>{if(e.target.id==="modal")$("modal").classList.remove("open")};
function render(){renderDash();renderProfile();renderAcademics();renderJourney("all");renderReflection();renderGrowth();renderOps();renderEvidence();renderPortfolio();renderFsa();renderApp()}
window.go=go;
init();
$("addReflection").onclick=async()=>{if(!experiences.length){alert("Please add an experience first.");return}$("modalBody").innerHTML="<h2>Add reflection</h2><label>Experience<select id=\"refExp\">"+experiences.map(x=>"<option value=\""+x.id+"\">"+esc(x.title)+"</option>").join("")+"</select></label><label>What happened?<textarea id=\"refH\"></textarea></label><label>What was your role?<textarea id=\"refR\"></textarea></label><label>What was difficult?<textarea id=\"refD\"></textarea></label><label>What decision did you make?<textarea id=\"refDec\"></textarea></label><label>What did you learn?<textarea id=\"refL\"></textarea></label><label>What changed?<textarea id=\"refC\"></textarea></label><label>What will you do next?<textarea id=\"refN\"></textarea></label><div class=\"modalactions\"><button id=\"saveReflection\" class=\"primary\">Save reflection</button></div>";$("modal").classList.add("open");$("saveReflection").onclick=async()=>{const q=await db.from("reflections").insert({user_id:user.id,experience_id:$("refExp").value,what_happened:$("refH").value.trim(),role_taken:$("refR").value.trim(),difficulty:$("refD").value.trim(),decision_made:$("refDec").value.trim(),learning:$("refL").value.trim(),what_changed:$("refC").value.trim(),next_step:$("refN").value.trim()});if(q.error){alert(q.error.message);return}closeModal();await load();render();go("reflection")}};\n$("addEvidence").onclick=()=>{$("modalBody").innerHTML="<p class=\"eyebrow\">EVIDENCE VAULT</p><h2>Add evidence</h2><label>Experience<select id=\"evx\">"+experiences.map(x=>"<option value=\""+x.id+"\">"+esc(x.title)+"</option>").join("")+"</select></label><label>Evidence title<input id=\"evt\"></label><label>Type<input id=\"evtype\" placeholder=\"Report / certificate / presentation / feedback / impact data\"></label><label>What does it prove?<textarea id=\"evnotes\"></textarea></label><div class=\"modalactions\"><button id=\"saveEvidence\" class=\"primary\">Save evidence</button></div>";$("modal").classList.add("open");$("saveEvidence").onclick=async()=>{let q=await db.from("evidence").insert({user_id:user.id,experience_id:$("evx").value,title:$("evt").value.trim(),evidence_type:$("evtype").value.trim()||"record",notes:$("evnotes").value.trim()});if(q.error)alert(q.error.message);closeModal();await load();render()}};
