const scholarships = [
{name:"NUS Global Merit Scholarship",provider:"National University of Singapore",levels:["University"],nationality:["Singapore Citizen"],field:"Multiple disciplines",award:"100% tuition + exchange + accommodation priority",deadline:"1 Feb–19 Mar 2026",source:"https://nus.edu.sg/oam/scholarships/scholarships-for-freshmen-singapore-citizens",verified:"2026-10-04"},
{name:"NUS Merit Scholarship",provider:"National University of Singapore",levels:["University"],nationality:["Singapore Citizen"],field:"Multiple disciplines",award:"Tuition + exchange + accommodation priority",deadline:"1 Feb–19 Mar 2026",source:"https://nus.edu.sg/oam/scholarships/scholarships-for-freshmen-singapore-citizens",verified:"2026-10-04"},
{name:"NUS Undergraduate Scholarship",provider:"National University of Singapore",levels:["University"],nationality:["Singapore Citizen"],field:"Multiple disciplines",award:"Tuition + exchange + accommodation priority",deadline:"1 Feb–19 Mar 2026",source:"https://nus.edu.sg/oam/scholarships/scholarships-for-freshmen-singapore-citizens",verified:"2026-10-04"},
{name:"NUS AI Talent Scholarship",provider:"National University of Singapore",levels:["University"],nationality:["Singapore Citizen"],field:"Artificial Intelligence",award:"Scholarship support",deadline:"1 Feb–19 Mar 2026",source:"https://nus.edu.sg/oam/scholarships/scholarships-for-freshmen-singapore-citizens",verified:"2026-10-04"},
{name:"NUS Science & Technology Undergraduate Scholarship",provider:"National University of Singapore",levels:["University"],nationality:["International","PR"],field:"Computing / Engineering / Science",award:"Tuition + living allowance",deadline:"Admissions timeline",source:"https://nus.edu.sg/oam/scholarships/scholarships-for-freshmen-permanent-residents",verified:"2026-10-04"},
{name:"NUS International Undergraduate Scholarship",provider:"National University of Singapore",levels:["University"],nationality:["International","PR"],field:"Multiple disciplines",award:"Scholarship support",deadline:"Admissions timeline",source:"https://www.nus.edu.sg/oam/scholarships/scholarships-for-freshmen-international-students",verified:"2026-10-04"},
{name:"NUS ASEAN Undergraduate Scholarship",provider:"National University of Singapore",levels:["University"],nationality:["ASEAN international"],field:"Multiple disciplines",award:"Scholarship support",deadline:"Admissions timeline",source:"https://www.nus.edu.sg/oam/scholarships/scholarships-for-freshmen-international-students",verified:"2026-10-04"},
{name:"NUS University Engineering Scholarship",provider:"National University of Singapore",levels:["Polytechnic","University"],nationality:["Singapore Citizen","PR"],field:"Engineering / Technology",award:"Scholarship support",deadline:"5–22 May 2026",source:"https://nus.edu.sg/oam/scholarships/scholarships-for-freshmen-singapore-citizens",verified:"2026-10-04"},
{name:"NUS LKY-STEP Award",provider:"NUS / partner universities",levels:["Polytechnic","University"],nationality:["Singapore Citizen","PR"],field:"Multiple disciplines",award:"Scholarship support",deadline:"11 May–2 Jun 2026",source:"https://nus.edu.sg/oam/scholarships/scholarships-for-freshmen-singapore-citizens",verified:"2026-10-04"},
{name:"PSC Scholarships",provider:"Public Service Commission",levels:["JC","University"],nationality:["Singapore Citizen"],field:"Multiple disciplines",award:"Public service scholarship",deadline:"Annual",source:"https://www.psc.gov.sg/scholarships/",verified:"2026-10-04"},
{name:"PSC Scholarships (Mid-Term)",provider:"Public Service Commission",levels:["University"],nationality:["Singapore Citizen"],field:"Multiple disciplines",award:"Public service scholarship",deadline:"Annual",source:"https://www.psc.gov.sg/scholarships/",verified:"2026-10-04"},
{name:"NUS Donated Scholarships",provider:"National University of Singapore",levels:["University"],nationality:["Various"],field:"Various",award:"Varies",deadline:"Varies",source:"https://www.nus.edu.sg/oam/scholarships/scholarships-for-current-nus-undergraduates/list-of-named-scholarships",verified:"2026-10-04"}
];